sudo: enabled
language: python
services:
  - redis
script:
  - pytest -v -s --cov=Chapter01 --cov-report term-missing
  - python app.py
before_script:
  - echo "Menjalankan Testing"
install:
  - pip install -r requirements.txt
before_install:
  - git status